# Generated by Django 5.1.3 on 2024-11-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Fmale", "Female"), ("Other", "Other")],
                default="O",
                max_length=7,
            ),
        ),
    ]
